import s from './ResultCard.module.css'

function normalizeClassName(value) {
  const cls = String(value || '').toLowerCase().trim()

  if (cls === 'diabetes' || cls === 'diabetic') {
    return {
      display: 'Diabetic',
      isDiabetic: true,
      message:
        'Tongue features show indicators associated with diabetes. Clinical confirmation required.',
    }
  }

  if (
    cls === 'nondiabetes' ||
    cls === 'non-diabetes' ||
    cls === 'non_diabetes' ||
    cls === 'nondiabetic' ||
    cls === 'non-diabetic'
  ) {
    return {
      display: 'Non-Diabetic',
      isDiabetic: false,
      message:
        'Tongue features appear within normal reference range. Not a clinical clearance.',
    }
  }

  return {
    display: value || 'Unknown',
    isDiabetic: false,
    message: 'Prediction result generated by the model.',
  }
}

function toPercent(value) {
  const num = Number(value)
  if (Number.isNaN(num)) return 0
  return num <= 1 ? num * 100 : num
}

function getProbability(probabilities, names) {
  if (!probabilities) return 0

  for (const name of names) {
    if (probabilities[name] !== undefined) {
      return toPercent(probabilities[name])
    }
  }

  return 0
}

export default function ResultCard({ result }) {
  const prediction = result?.prediction || result?.pred_class
  const classInfo = normalizeClassName(prediction)

  const confidence = toPercent(result?.confidence)

  const diabeticProb = getProbability(result?.probabilities, [
    'diabetes',
    'Diabetic',
    'diabetic',
  ])

  const nonDiabeticProb = getProbability(result?.probabilities, [
    'nondiabetes',
    'Non-Diabetic',
    'non-diabetic',
    'nondiabetic',
  ])

  return (
    <div
      className={[
        s.card,
        classInfo.isDiabetic ? s.cardDanger : s.cardSafe,
      ].join(' ')}
    >
      <div className={s.header}>
        <span
          className={[
            s.statusPill,
            classInfo.isDiabetic ? s.statusDanger : s.statusSafe,
          ].join(' ')}
        >
          <span className={s.dot} />
          {classInfo.display}
        </span>

        <span className={s.modelName}>EfficientNet-B1 + CBAM</span>
      </div>

      <div className={s.body}>
        <div className={s.confidenceBlock}>
          <span className={s.confidenceValue}>
            {confidence.toFixed(2)}
          </span>
          <span className={s.confidenceLabel}>% confidence</span>
        </div>

        <div className={s.probList}>
          <ProbabilityRow
            label="Diabetic"
            value={diabeticProb}
            danger
          />

          <ProbabilityRow
            label="Non-Diabetic"
            value={nonDiabeticProb}
          />
        </div>

        <div className={s.messageBox}>
          {classInfo.message}
        </div>

        <p className={s.disclaimer}>
          Research use only · Not a substitute for medical diagnosis
        </p>
      </div>
    </div>
  )
}

function ProbabilityRow({ label, value, danger }) {
  return (
    <div className={s.probRow}>
      <span className={s.probLabel}>{label}</span>

      <div className={s.barTrack}>
        <div
          className={[
            s.barFill,
            danger ? s.barDanger : s.barSafe,
          ].join(' ')}
          style={{
            width: `${Math.min(Math.max(value, 0), 100)}%`,
          }}
        />
      </div>

      <span className={s.probValue}>{value.toFixed(2)}%</span>
    </div>
  )
}